site_name: Mad-Assembler
site_author: TeBe
site_description: "Mad-Assembler Documentation"

repo_url: https://github.com/tebe6502/mad-assembler-mkdocs/
edit_uri: ""

theme:
    name: readthedocs
    highlightjs: true
    hljs_style: dark
    hljs_languages:
        - armasm

nav:
    - Introduction: introduction.md
    - Usage: usage.md
    - Assembly control: control.md
    - Sparta DOS X: spartadosx.md
    - Syntax: syntax.md
    - Labels: labels.md
    - Mnemonics: mnemonics.md
    - Macro Commands: macro-commands.md
    - Pseudo Commands: pseudo-commands.md
    - Directives: directives.md
    - Local Areas: local-areas.md
    - Procedures: procedures.md
    - Macros: macros.md
    - Code Generation Directives: code-generation-directives.md
    - Arrays: arrays.md
    - Data Types: data-types.md
    - CPU Detection: cpu-detection.md
    - Memory Banks: memory-banks.md
    - Relocatable Code: relocatable-code.md
    - Examples: examples.md
    - Projects: projects.md
